name: Moving Forward
favicon: null
layout_spectrum: 0.24678
typography_spectrum: 0.39118
title: From Within
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#1b120d'
    - '#4f6a7f'
    - '#333644'
    - '#668234'
    - '#85a159'
  brandStrength: 0.5
  lightness: 0.5
  saturation: 0.10827458603307605
  rhythmicContrast: 0.40367250493727624
purpose: []
